version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      # Check if the build successfully finished and we have a bundle in the out dir
      - FILE_COUNT=$(find $CODEBUILD_SRC_DIR/out -type f | wc -l)
      - if [ "$FILE_COUNT" -gt "0" ]; then
        - echo `ls`
        # Empty bucket before adding new scripts
        - aws s3 rm s3://aidanlowson.com --recursive
        # Remove cloudFront cache
        # --paths "./index.html" "./build/*" "./asset-manifest.json"
        - aws cloudfront create-invalidation
          --distribution-id E1MWBYTX2PMKXG
          --paths "/*"
        # Move built files
        # Copy the contents of /build to S3
        - aws s3 cp --recursive --acl public-read ./out s3://aidanlowson.com
      else
        echo Build failed and /out dir is empty, skipping post_build commands
      fi
artifacts:
  files:
    - './out/*'
