version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo `ls`
      # Empty bucket before adding new scripts
      - aws s3 rm s3://aidanlowson.com --recursive
      # Remove cloudFront cache
      # --paths "./index.html" "./build/*" "./asset-manifest.json"
      - aws cloudfront create-invalidation
        --distribution-id E1MWBYTX2PMKXG
        --paths "/*"
      # Move built files
      # Copy the contents of /build to S3
      - aws s3 cp --recursive --acl public-read ./build s3://aidanlowson.com
artifacts:
  files:
    - "./build/*"
