version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
    build:
      commands:
        - echo Build started on `date`
        - npm run build
      post_build:
        commands:
          # Copy the contents of /build to S3
          - aws s3 cp --recursive --acl public-read ./frontend/build s3://${DeployBucket}
          # Prevent browser caching
          --cache-control="max-age=0, no-cache, no-store, must-revalidate"
          ./frontend/build/service-worker.js s3://${DeployBucket}/