version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
      - npm start
  build:
    commands:
      - npm run cypress:test