version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
      - npm run dev &
  build:
    commands:
      - npm run cypress:test