version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - yum install -y atk at-spi2-atk gtk3 mesa-libgbm
      - npm install -g pnpm
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
      - npm run dev &
  build:
    commands:
      - npm run cypress:test